Add Outputs

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -37,13 +37,18 @@ jobs:
           domains: ${{ env.DOMAINS }}
           dry_run: true
 
-      #- name: "Validate Outputs"
-      #  run: |
-      #    echo "domains: '${{ steps.test.outputs.domains }}'"
-      #    if [ -z '${{ steps.test.outputs.domains }}' ];then
-      #      echo "No Output: domains"
-      #      exit 1
-      #    fi
+      - name: "Validate Outputs"
+        run: |
+          echo "success: '${{ steps.test.outputs.success }}'"
+          if [ "${{ steps.test.outputs.success }}" != "cssnr.com" ];then
+            echo "Output Verification Failed: success"
+            exit 1
+          fi
+          echo "failed: '${{ steps.test.outputs.failed }}'"
+          if [ "${{ steps.test.outputs.failed }}" != "example.com" ];then
+            echo "Output Verification Failed: failed"
+            exit 1
+          fi
 
   lint:
     name: "Lint"
