Update Workflows

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,5 +1,7 @@
 name: "Test"
 
+# actions-up-ignore-file
+
 on:
   workflow_dispatch:
   schedule:
@@ -12,7 +14,7 @@ on:
       - "src/**"
       - "package*.json"
       - "requirements*.txt"
-      - "action.y*l"
+      - "action.yaml"
       - "Dockerfile"
       - "pyproject.toml"
 
@@ -42,11 +44,11 @@ jobs:
       - name: "Checkout"
         uses: actions/checkout@v5
 
-      #- name: "Debug Event"
-      #  if: ${{ !github.event.act }}
-      #  continue-on-error: true
-      #  run: |
-      #    cat "${GITHUB_EVENT_PATH}"
+      - name: "Debug event.json"
+        if: ${{ !github.event.act }}
+        continue-on-error: true
+        run: |
+          cat "${GITHUB_EVENT_PATH}"
 
       - name: "Debug CTX github"
         if: ${{ !github.event.act }}
@@ -54,6 +56,12 @@ jobs:
         env:
           GITHUB_CTX: ${{ toJSON(github) }}
         run: echo "$GITHUB_CTX"
+
+      - name: "Debug Environment"
+        if: ${{ !github.event.act }}
+        continue-on-error: true
+        run: |
+          env
 
       - name: "Edit YAML"
         if: ${{ !github.event.act }}
@@ -78,19 +86,27 @@ jobs:
           hosts: ${{ env.HOSTS }}
           prefixes: ${{ env.PREFIXES }}
 
-      - name: "Verify Outputs"
-        if: ${{ env.ZONES == 'cssnr.com,example.com' }}
-        run: |
-          echo "success: '${{ steps.test.outputs.success }}'"
-          if [ "${{ steps.test.outputs.success }}" != "cssnr.com" ];then
-            echo "Output Verification Failed: success"
-            exit 1
-          fi
-          echo "failed: '${{ steps.test.outputs.failed }}'"
-          if [ "${{ steps.test.outputs.failed }}" != "example.com" ];then
-            echo "Output Verification Failed: failed"
-            exit 1
-          fi
+      - name: "Validate Outputs"
+        uses: cssnr/validate-outputs-action@master
+        with:
+          outputs: ${{ toJSON(steps.test.outputs) }}
+          data: |
+            success: cssnr.com
+            failed: example.com
+
+      #- name: "Verify Outputs"
+      #  if: ${{ env.ZONES == 'cssnr.com,example.com' }}
+      #  run: |
+      #    echo "success: '${{ steps.test.outputs.success }}'"
+      #    if [ "${{ steps.test.outputs.success }}" != "cssnr.com" ];then
+      #      echo "Output Verification Failed: success"
+      #      exit 1
+      #    fi
+      #    echo "failed: '${{ steps.test.outputs.failed }}'"
+      #    if [ "${{ steps.test.outputs.failed }}" != "example.com" ];then
+      #      echo "Output Verification Failed: failed"
+      #      exit 1
+      #    fi
 
       - name: "Schedule Failure Notification"
         if: ${{ failure() && github.event_name == 'schedule' }}
